### ISSUE TITLE
Fix orekit dependency v10.2

### ISSUE THREAD

**Issue by YgabrielsY** [SISPO-developers/sispo#219]

**Comment by thvaisa** [comment]
How complicated issue is this and if I run Sispo, when should I expect to see the conflict?

**Comment by YgabrielsY** [comment]
The issue is fixed and only needs to be merged. You can check the commit to see what needs to be changed if you want to change it in your local installation.
The problem occurs as soon as the propagator starts with the first step since the `Action.CONTINUE` has been moved
