### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by thvaisa** [SISPO-developers/sispo#227]
The Readme has a line "Currently, a problem exists with the mathutils import in the sim.py. An import of bpy must be done before running sispo."

Is this relevant anymore? At least, I have never encountered this (entire 2020).

**Comment by YgabrielsY** [comment]
If running an `import sispo` with an interactive shell, this error should still exist since mathutils is imported before bpy, however mathutils is part of bpy unless you downloaded the separate mathutils python module.
